stages:
- name: Upload to AI Orchestrator
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        #!/bin/sh
        file="$(pwd)"
        gitjson='{"type":"git","name":"'$title'","description":"'$description'", "image": {"name":"'$imagename'","execparameters":"'$execparameters'"}, "git": {"url":"'${CICD_GIT_URL}'"}}'
        curl  -i -X POST -H "Content-Type: multipart/form-data"\
                 -F data="$gitjson" \
                 -X POST  http://192.168.1.24:2200/api/pipe/upload
    env:
      description: Demo from Rancher pipelines
      execparameters: pip install -r demo03/requirements.txt && jupyter nbconvert
        --to html --execute demo03/demo.ipynb --ExecutePreprocessor.timeout=-1 --output-dir=output
      imagename: python
      title: DemoRancher
timeout: 60
notification: {}
