plugin-name: katib
namespace: "kubeflow"
yaml:
  - url: "github.com/kubeflow/manifests/tf-training/tf-job-crds/base"
    type: "kustomize"  
  - url: "github.com/kubeflow/manifests/tf-training/tf-job-operator/base"
    type: "kustomize"
  - url: "github.com/kubeflow/manifests/pytorch-job/pytorch-job-crds/base"
    type: "kustomize"  
  - url: "github.com/kubeflow/manifests/pytorch-job/pytorch-operator/base"
    type: "kustomize"  
  - url: "github.com/kubeflow/manifests/katib/components/katib-crds"
    type: "kustomize"
  - url: "github.com/kubeflow/manifests/katib/components/katib-controller"
    type: "kustomize"
  - url: "github.com/kubeflow/manifests/katib/components/katib-db-manager"
    type: "kustomize"
  - url: "github.com/kubeflow/manifests/katib/components/atib-db-mysql"
    type: "kustomize"
