plugin-name: katib
namespace: "kubeflow"
yaml:
  - url: "github.com/kubeflow/manifests/tf-training/tf-job-crds/base"
    type: "kustomize"  
  - url: "github.com/kubeflow/manifests/tf-training/tf-job-operator/base"
    type: "kustomize"
  - url: "github.com/kubeflow/manifests/pytorch-job/pytorch-job-crds/base"
    type: "kustomize"  
  - url: "github.com/kubeflow/manifests/pytorch-job/pytorch-operator/base"
    type: "kustomize"  
  - url: "github.com/kubeflow/manifests/katib/installs/katib-standalone"
    type: "kustomize"
