ugin-name: katib
namespace: "kubeflow"
yaml:
  - url: "github.com/kubeflow/manifests/tf-training/tf-job-crds/base"
    type: "kustomize"  
  - url: "github.com/kubeflow/manifests/tf-training/tf-job-operator/base"
    type: "kustomize"
  - url: "github.com/kubeflow/manifests/pytorch-job/pytorch-job-crds/base"
    type: "kustomize"  
  - url: "github.com/kubeflow/manifests/pytorch-job/pytorch-operator/base"
    type: "kustomize"  

  - url: "github.com/kubeflow/manifests/katib/katib-crds/base/experiment-crd.yaml"
    type: "file"
  - url: "github.com/kubeflow/manifests/katib/katib-crds/base/suggestion-crd.yaml"
    type: "file"
  - url: "github.com/kubeflow/manifests/katib/katib-crds/base/trial-crd.yaml"
    type: "file"
  - url: "github.com/kubeflow/manifests/katib/katib-crds/overlays/application/application.yaml"
    type: "file"

  - url: "github.com/kubeflow/manifests/katib/katib-controller/base"
    type: "kustomize"
  - url: "github.com/kubeflow/manifests/katib/katib-controller/overlays/application/application.yaml"
    type: "file"

  - url: "github.com/kubeflow/manifests/katib/katib-controller/overlays/application/application.yaml"
    type: "file"
